server.port=8080

# Stockfish configuration
stockfish.download-url=https://github.com/official-stockfish/Stockfish/releases/latest/download/stockfish-windows-x86-64-sse41-popcnt.zip
stockfish.binary-dir=./bin
stockfish.binary-path=./bin/stockfish.exe

# Maximum time (in milliseconds) the engine can think per move
stockfish.default-movetime=1000
# Default depth the engine will search
stockfish.default-depth=15
# Default ELO rating target
stockfish.default-elo=3200
